-- AlterTable
ALTER TABLE "listings" ADD COLUMN     "image_a_zoom" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "image_am_zoom" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "image_c_zoom" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "image_cm_zoom" INTEGER NOT NULL DEFAULT 100,
ADD COLUMN     "image_zoom" INTEGER NOT NULL DEFAULT 100;
