"use client";
import { useState } from "react";
import { ArrowRight, Check, Heart, Headphones, Trophy, Volume2, X, Zap } from "lucide-react";
import { cn } from "@/lib/utils";

const questions = [
  { uz: "Salom", en: "Hello", phonetic: "/həˈləʊ/", options: ["Hello", "Goodbye", "Please", "Thanks"], answer: 0 },
  { uz: "Xayr", en: "Goodbye", phonetic: "/ˌɡʊdˈbaɪ/", options: ["Sorry", "Yes", "Goodbye", "Hello"], answer: 2 },
  { uz: "Rahmat", en: "Thank you", phonetic: "/ˈθæŋk juː/", options: ["Please", "Thank you", "No", "Sorry"], answer: 1 },
];
export function LessonOverlay({ accent, ink, background, square = false, onClose }: { accent: string; ink: string; background: string; square?: boolean; onClose: () => void }) {
  const [index, setIndex] = useState(0), [selected, setSelected] = useState<number | null>(null), [done, setDone] = useState(false); const q = questions[index];
  if (done) return <div className="fixed inset-0 z-[150] grid place-items-center p-5" style={{ background }}><div className={cn("w-full max-w-xl bg-white p-10 text-center shadow-2xl", !square && "rounded-[30px]")}><span className="mx-auto grid size-24 place-items-center rounded-full" style={{ background: `${accent}20`, color: accent }}><Trophy className="size-11" /></span><p className="mt-6 text-xs font-black uppercase tracking-[.2em]" style={{ color: accent }}>Birinchi dars tugadi</p><h2 className="mt-2 font-heading text-5xl font-semibold" style={{ color: ink }}>Barakalla!</h2><p className="mt-3 text-sm text-black/50">3 ta yangi ibora va +30 XP bilim sandig‘ingizga qo‘shildi.</p><button onClick={onClose} className="mt-7 inline-flex items-center gap-2 px-7 py-4 font-black text-white" style={{ background: accent, borderRadius: square ? 0 : 16 }}>Davom etish <ArrowRight /></button></div></div>;
  return <div className="fixed inset-0 z-[150] overflow-y-auto p-4 sm:p-8" style={{ background }}><div className="mx-auto max-w-5xl"><div className="mb-6 flex items-center gap-4" style={{ color: ink }}><button onClick={onClose} className="grid size-10 place-items-center rounded-full border border-current/15"><X /></button><div className="h-2 flex-1 overflow-hidden rounded-full bg-black/10"><div className="h-full" style={{ width: `${((index + (selected !== null ? 1 : 0)) / questions.length) * 100}%`, background: accent }} /></div><Heart className="fill-current" style={{ color: accent }} /></div><div className={cn("grid overflow-hidden bg-white shadow-2xl md:grid-cols-[.8fr_1.2fr]", !square && "rounded-[30px]")}><aside className="flex min-h-64 flex-col justify-between p-8 text-white md:min-h-[520px]" style={{ background: ink }}><span className="text-xs font-black uppercase tracking-[.2em] opacity-40">Expression 0{index + 1}</span><div><button className="mb-5 grid size-12 place-items-center rounded-full" style={{ background: accent }}><Volume2 /></button><h1 className="font-heading text-6xl font-semibold italic">{q.en}</h1><p className="mt-3 opacity-45">{q.phonetic}</p></div><p className="flex items-center gap-2 text-xs font-bold opacity-40"><Headphones className="size-4" /> Eshiting va takrorlang</p></aside><section className="p-7 sm:p-10" style={{ color: ink }}><div className="flex justify-between text-[10px] font-black uppercase tracking-wider opacity-40"><span>Tarjimani toping</span><span><Zap className="inline size-3" /> +10 XP</span></div><h2 className="mt-5 text-3xl font-black">“{q.uz}” inglizchada qanday?</h2><div className="mt-7 grid gap-3">{q.options.map((option, i) => { const show = selected !== null, good = i === q.answer, picked = i === selected; return <button key={option} onClick={() => setSelected(i)} disabled={show} className={cn("flex items-center gap-3 border-2 p-4 text-left font-bold", !square && "rounded-2xl", !show && "border-black/10 hover:border-black", show && good && "border-emerald-500 bg-emerald-50 text-emerald-700", show && picked && !good && "border-rose-500 bg-rose-50 text-rose-700", show && !picked && !good && "opacity-30")}><span className="grid size-7 place-items-center rounded-lg border border-current/20 text-xs">{show && good ? <Check className="size-4" /> : String.fromCharCode(65 + i)}</span>{option}</button>; })}</div><button disabled={selected === null} onClick={() => { if (index === questions.length - 1) setDone(true); else { setIndex((n) => n + 1); setSelected(null); } }} className="mt-6 w-full p-4 font-black text-white disabled:opacity-20" style={{ background: accent, borderRadius: square ? 0 : 16 }}>Davom etish</button></section></div></div></div>;
}
export function FooterColumns({ title, text, dark = false }: { title: string; text: string; dark?: boolean }) { return <footer className={cn("border-t px-6 pb-28 pt-12", dark ? "border-white/10" : "border-black/10")}><div className="mx-auto grid max-w-7xl gap-8 md:grid-cols-[1.2fr_1fr]"><div><b className="font-heading text-2xl">{title}</b><p className="mt-2 max-w-sm text-sm opacity-45">{text}</p></div><div className="grid grid-cols-3 gap-5 text-xs">{[["O‘RGANISH","Darslar","Mashqlar"],["JAMOA","Do‘stlar","Reyting"],["ALOQA","Yordam","Biz haqimizda"]].map((col) => <div key={col[0]}><b className="opacity-35">{col[0]}</b><p className="mt-3">{col[1]}</p><p className="mt-2">{col[2]}</p></div>)}</div></div></footer>; }
